### ISSUE TITLE
Pindah 0.1.1 regression: Project fails to compile

### ISSUE THREAD

**Issue by sattvik** [mirah/pindah#13]
I have a project that builds fine with 0.1.0, but now fails to build with 0.1.1.  I have not yet fully had the time to track it down, but I think that somehow the generated R class isn't being included in mirahc's classpath.

I will look into this a bit more and submit a patch once I have figured out what's going on.

**Comment by sattvik** [comment]
I found out what is going on, but do not have a fix, yet.  It seems like the mirahc task is messing up the package for mirah sources.  As an example, let's say the root directory for your project is '/home/foo/myproject'.  The source file is 'src/myproject/foo.mirah'.  The compiled class should be 'bin/classes/myproject/Foo.class', but instead it's showing up as 'bin/classes/home/foo/myproject/Foo.class'.  So, so far as I can tell, this is probably a Mirah bug.

**Comment by sattvik** [comment]
Just sent a pull request that fixes the issue.

**Comment by LarsWestergren** [comment]
I still have this issue unfortunately, even when applying your change to build.xml. I'm using Mirah v0.0.7

**Comment by takeru** [comment]
same problem

http://groups.google.com/group/mirah/browse_thread/thread/f8ecc74daa1eba2d

works for me!

tkrmb2:~/proj/mirah-android/HelloPindah% gem list

**\* LOCAL GEMS ***

arrayfields (4.7.4)
bitescript (0.0.8)
bouncy-castle-java (1.5.0146.1)
bundler (1.0.13)
fattr (2.2.0)
jruby-jars (1.6.1)
jruby-openssl (0.7.4)
main (4.2.0)
mirah (0.0.7 java)
pindah (0.1.1)
rake (0.8.7)
ruboto-core (0.1.0)
tkrmb2:~/proj/mirah-android/HelloPindah% ruby -v
jruby 1.6.1 (ruby-1.8.7-p330) (2011-04-12 85838f6) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_24) [darwin-x86_64-java]

&lt;taskdef name="mirahc" classname="org.mirah.ant.Compile" /&gt;
calls this:
https://github.com/mirah/mirah/blob/master/src/org/mirah/ant/compile.duby

**Comment by zapnap** [comment]
Applied patch, sorry for the delay here.
