### ISSUE TITLE
javac task in build.xml should include the classpath used by mirahc task

### ISSUE THREAD

**Issue by igstan** [mirah/pindah#18]
I think the `javac` task in `templates/build.xml` should look like this:

```
 <javac srcdir="gen" destdir="${classes}"
            classpath="${classpath}"
            includeantruntime="false" failonerror="true" />
```

The reason is that, if I have aidl files in my src directory, at compile basic packages like android.os won't be available. Like this project for example: https://github.com/couchone/libcouch-android/tree/master/src/com/couchone/libcouch

I just took those two aidl files (completed with package names) and put names in the src directory that `pindah create` is producing. jrake debug will fail with something like this:

```
javac:
Compiling 3 source files to /Users/user/Projects/android/mirah/hello/bin/classes
/Users/user/Projects/android/mirah/hello/gen/com/couchone/libcouch/ICouchClient.java:6: package android.os does not exist
public interface ICouchClient extends android.os.IInterface
                                                ^
```

**Comment by AtomicPair** [comment]
Hi, @igstan.  This issue should be covered by the upcoming changes in the 0.1.3 release, so I'm closing this issue.  If you're still experiencing issues after the 0.1.3. release, please open a new issue with the relevant error information.
