### ISSUE TITLE
does pindah support library reference

### ISSUE THREAD

**Issue by niedhui** [mirah/pindah#20]
eg :
in default.properties
android.library.reference.1=../../xxxx

rake compile 
seems it doesn't compile the reference library into the bin folder

**Comment by abscondment** [comment]
Hey @niedhui -- could you test this out? It's working pretty well for me.

**Comment by abscondment** [comment]
My project is successfully compiling against the Facebook SDK and some other sundry libraries, so I'm going to mark this as closed.

The new syntax looks like this:

``` ruby
Pindah.spec = {
  ...
  :libraries => ["../facebook", "../pulltorefresh"]
}
```

The ant task seems to be really strict about where libraries are -- I have only had it work when the libraries share a parent directory with your project.
