### ISSUE TITLE
pindah should force Mirah to generate Java 1.6 bytecode

### ISSUE THREAD

**Issue by tlwalker** [mirah/pindah#25]
There should be a way have Mirah generate a specific version of JVM bytecode or have the Pindah build script compile the Mirah-generated Java source code compiled as a step. This is to address the fact that Java 7 is not supported the Android SDK.

**Comment by baroquebobcat** [comment]
you mean like the `--jvm` option on `mirahc`?

**Comment by tlwalker** [comment]
Yes, I believe that is it. Having the mirahc task run as mirachc --jvm 1.6 when run on a system with 1.7 installed would fix this until android supports Java 7. I would say mirror the javac task but the target attribute is already taken. So I guess a jvm or target-jvm attribute would work.

**Comment by baroquebobcat** [comment]
Added a new Mirah issue for this (https://github.com/mirah/mirah/issues/156). it should be a pretty straight forward change on the Mirah side.

**Comment by tlwalker** [comment]
Cool. By the way, there also needs to be an addition in the target and source attributes to the javac entry in pindah's build.xml file.

**Comment by abscondment** [comment]
Ah, looks like we just fixed this. Sorry 'bout the lag.
