### ISSUE TITLE
Builds currently shell out to a separate mirahc process

### ISSUE THREAD

**Issue by technomancy** [mirah/pindah#6]
Builds would be faster if they used the Mirah ant task instead, but it currently doesn't set the classpath correctly, so R classes are not available.

**Comment by ribrdb** [comment]
If you're using ant for compiling java files, you should be able to use the same classpath for mirahc as javac.  There's an example in my gwt build.xml: https://github.com/ribrdb/mirah_gwt_example/blob/master/build.xml

**Comment by technomancy** [comment]
Set classpath correctly for mirahc ant task. Closed by 8cb47dccc46579b7947e873104713f2147363a15.
