### ISSUE TITLE
Failed tasks do not stop the build process.

### ISSUE THREAD

**Issue by technomancy** [mirah/pindah#7]
Compilation errors in the mirahc stage will still cause the app (whatever version is already on disk) to be installed in "jrake install"

(This is true only when the compiler is invoked using the org.mirah.ant.Compile task; shelling out with exec works properly.)

**Comment by abscondment** [comment]
What's the rationale for calling the ant.Compile task rather than using exec? This is a pretty frustrating bug, especially when you get in the habit of running `rake install && adb logcat`.

**Comment by technomancy** [comment]
I believe exec will spawn another JVM, so you pay startup costs for the redundant process.

**Comment by abscondment** [comment]
That makes sense. I submitted a fix on the mirah side of things; think you can test it out?

https://github.com/mirah/mirah/pull/140

**Comment by abscondment** [comment]
This is stale; the issue was fixed by mirah/mirah#140.
